version: "3.8"
services:
  auth:
    build: ./auth
    container_name: auth-container
    depends_on:
      - auth-db
      - redpanda
    develop:
      watch:
        - action: sync
          path: ./auth
          target: ./auth
          ignore:
            - node_modules/
        - action: rebuild
          path: ./auth/package.json
        - action: rebuild
          path: ./auth/package-lock.json
    environment:
      MONGO_URL: mongodb://auth-db:27017/auth
      KAFKA_BROKER: redpanda:29092
      JWT_SECRET: blablablablablablabal
    ports:
      - 4000:4000

  users:
    build: ./users
    container_name: users-container
    depends_on:
      - users-db
      - redpanda
    develop:
      watch:
        - action: sync
          path: ./users
          target: ./users
          ignore:
            - node_modules/
        - action: rebuild
          path: ./users/package.json
        - action: rebuild
          path: ./users/package-lock.json
    environment:
      MONGO_URL: mongodb://users-db:27017/users
      KAFKA_BROKER: redpanda:29092
      JWT_SECRET: blablablablablablabal
    ports:
      - 5000:5000

  company:
    build: ./company
    container_name: company-container
    depends_on:
      - company-db
      - redpanda
    develop:
      watch:
        - action: sync
          path: ./company
          target: ./company
          ignore:
            - node_modules/
        - action: rebuild
          path: ./company/package.json
        - action: rebuild
          path: ./company/package-lock.json
    environment:
      MONGO_URL: mongodb://company-db:27017/company
      KAFKA_BROKER: redpanda:29092
      JWT_SECRET: blablablablablablabal
    ports:
      - 8080:8080

  communication:
    build: ./communication
    container_name: communication-container
    depends_on:
      - communication-db
      - redpanda
    develop:
      watch:
        - action: sync
          path: ./communication
          target: ./communication
          ignore:
            - node_modules/
        - action: rebuild
          path: ./communication/package.json
        - action: rebuild
          path: ./communication/package-lock.json
    environment:
      MONGO_URL: mongodb://communication-db:27017/communication
      KAFKA_BROKER: redpanda:29092
      JWT_SECRET: blablablablablablabal
    ports:
      - 8000:8000

  client:
    build: ./client
    container_name: client-container
    develop:
      watch:
        - action: sync
          path: ./client
          target: ./client
          ignore:
            - node_modules/
        - action: rebuild
          path: ./client/package.json
        - action: rebuild
          path: ./client/package-lock.json
    ports:
      - 3000:3000

  ai:
    build: ./ai
    container_name: ai-container
    develop:
      watch:
        - action: sync
          path: ./ai
          target: ./ai
          ignore:
            - node_modules/
        - action: rebuild
          path: ./ai/package.json
        - action: rebuild
          path: ./ai/package-lock.json
    environment:
      KAFKA_BROKER: redpanda:29092
      JWT_SECRET: blablablablablablabal11
    ports:
      - 7000:7000

  auth-db:
    image: mongo:7.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - auth_db:/data/db

  company-db:
    image: mongo:7.0
    restart: always
    ports:
      - 27018:27017
    volumes:
      - compnay_db:/data/db

  users-db:
    image: mongo:7.0
    restart: always
    ports:
      - 27019:27017
    volumes:
      - users_db:/data/db

  communication-db:
    image: mongo:7.0
    restart: always
    ports:
      - 27020:27017
    volumes:
      - communication_db:/data/db

  redpanda:
    image: docker.redpanda.com/vectorized/redpanda:v22.2.2
    container_name: carreralink-redpanda
    command:
      - redpanda start
      - --kafka-addr PLAINTEXT://0.0.0.0:29092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092
    ports:
      - 29092:29092

volumes:
  auth_db:
    name: auth-data
  users_db:
    name: users-data
  compnay_db:
    name: company-data
  communication_db:
    name: communication-data
