apiVersion: v1
kind: Secret
metadata:
  name: google-secret
type: Opaque
data:
  GOOGLE_AI_API_KEY: QUl6YVN5QWlEQ0YxMEJZUFVoVWlnNTBuY3FXTFhhSWFtQmd3dW04
  NEXT_PUBLIC_GOOGLE_CLIENT_ID: NDQ0MDU1MDEwODY5LWllOTQ2aGk5NDF1MWhjc2Yxb244dnA2YTMzZXFpZ2dzLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  NEXT_PUBLIC_GOOGLE_CLIENT_SECRET: R09DU1BYLUgyclo2M0JNRzBKbzhVNWVpcDIyd3lUSF95emk=
  
