apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
data:
  STRIPE_PUBLISHABLE_KEY: cGtfdGVzdF81MVA4ZmJjU0kzcHZ4QkZBQjRYOEJqbGJiRzU4eUxjS2RZSUZQZjgyQThibXE5aEdOQTRQaHdmSmRSYXFRNEh5THdFYmo3ZXNKT1VBNWs4MlRGMkZZVXowSzAwQXk3ZFFpNkY=
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVA4ZmJjU0kzcHZ4QkZBQkVaZktVRTduRm5VbFZ5M3dZYW44bDk5alJtOWxhUm1FWXJpR2I0OHR2THJ6T1NDRHc4YzZQMmt3MXBxamR0RlJpazlVd0laMTAwVUt0ak5oZnQ=
