apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
        - name: ai
          image: ajmalj/carreralink-ai
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: PRODUCTION_URL
              valueFrom:
                secretKeyRef:
                  name: static-secret
                  key: PRODUCTION_URL
            - name: GOOGLE_AI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: google-secret
                  key: GOOGLE_AI_API_KEY
            - name: KAFKA_BROKER
              value: kafka-service:9092
            - name: IS_PRODUCTION
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  selector:
    app: ai
  ports:
    - name: ai
      protocol: TCP
      port: 7000
      targetPort: 7000
