apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication
  template:
    metadata:
      labels:
        app: communication
    spec:
      containers:
        - name: communication
          image: ajmalj/carreralink-communication
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URL
              value: "mongodb://communication-db-service:27017/communication"
            - name: KAFKA_BROKER
              value: kafka-service:9092
            - name: IS_PRODUCTION
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: communication-service
spec:
  selector:
    app: communication
  ports:
    - name: communication
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  type: NodePort
