apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: ajmalj/carreralink-user
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URL
              value: "mongodb://user-db-service:27017/user"
            - name: KAFKA_BROKER
              value: kafka-service:9092
            - name: IS_PRODUCTION
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 5000
      targetPort: 5000
