apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-db
  template:
    metadata:
      labels:
        app: admin-db
    spec:
      containers:
        - name: admin-db
          image: mongo:7.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: admin-storage
              mountPath: /data/db
      volumes:
        - name: admin-storage
          persistentVolumeClaim:
            claimName: admin-storage

---
apiVersion: v1
kind: Service
metadata:
  name: admin-db-service
spec:
  selector:
    app: admin-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
