apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication-db
  template:
    metadata:
      labels:
        app: communication-db
    spec:
      containers:
        - name: communication-db
          image: mongo:7.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: communication-storage
              mountPath: /data/db
      volumes:
        - name: communication-storage
          persistentVolumeClaim:
            claimName: communication-storage

---
apiVersion: v1
kind: Service
metadata:
  name: communication-db-service
spec:
  selector:
    app: communication-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
