apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company-db
  template:
    metadata:
      labels:
        app: company-db
    spec:
      containers:
        - name: company-db
          image: mongo:7.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: company-storage
              mountPath: /data/db
      volumes:
        - name: company-storage
          persistentVolumeClaim:
            claimName: company-storage

---
apiVersion: v1
kind: Service
metadata:
  name: company-db-service
spec:
  selector:
    app: company-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
